env:
  global:
    - CC_TEST_REPORTER_ID=6bdf928af38529955b976480e38018d63e64087331ba7ed6eb3c645934677833

sudo: false

language: generic

cache:
  directories:
  - blender

env: # build matrix
  - BLENDER_VERSION=2.77
  - BLENDER_VERSION=2.78
  - BLENDER_VERSION=2.79

install:
  - sh ./tests/ci-prepare.sh

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./blender-$BLENDER_VERSION/blender --factory-startup -noaudio -b --python-exit-code 1 --python tests/runner.py

after_success:
  - sh ./tests/ci-report.sh
